### ISSUE TITLE
Binary encoding is not correct/compatible

### ISSUE THREAD

**Issue by postspectacular** [mafintosh/uint64be#1]
Even though the roundtrip encoding works within your library, its binary representation is not what it should be and would cause issues with other tooling:

```js
// current
uint64be.encode(Math.pow(2, 53)-1)
<Buffer 00 20 00 00 00 1f ff ff>

// expected
<Buffer 00 1f ff ff ff ff ff ff>
```

This can be easily fixed by changing: `const UINT_32_MAX = Math.pow(2, 32);`

**Comment by mafintosh** [comment]
Well thats embarrassing. Thanks for the fix though.

**Comment by mafintosh** [comment]
Out in 2.0.0
