### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by jimmywarting** [mafintosh/uint64be#4]
Maybe deprecate this npm package in favor of:
- [DataView.prototype.getBigInt64](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigInt64)
- [DataView.prototype.getBigUInt64](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigUInt64)

**Comment by mafintosh** [comment]
Thanks, but this is pretty heavily used by a lot of things I run.

**Comment by jimmywarting** [comment]
Then how about just a recommendation in the top of the readme that suggest using DataView for newcomers?
